apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app: cfcovid
  name: cfcovid
  namespace: cfcovid
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: cfcovid
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cfcovid
  name: cfcovid
  namespace: cfcovid
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cfcovid
  template:
    metadata:
      labels:
        app: cfcovid
    spec:
      containers:
        - env:
          image: >-
            sergepoueme/cfcovid:latest
          imagePullPolicy: IfNotPresent
          name: cfcovid
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          resources: {}
